apiVersion: apps/v1
kind: Deployment
metadata:
  name: bca-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bca-api
  template:
    metadata:
      labels:
        app: bca-api
    spec:
      containers:
      - name: bca-api
        image: mhlychol/bca-api:1.0
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 1 
